apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.FULL_NAME" . }}-pvc
  namespace: jimber
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  storageClassName: rook-cephfs
