name: threebotlogin
description: A new Flutter project.

version: 1.4.0+56

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  password_hash:
  intl: ^0.15.8
  flutter:
    sdk: flutter
  qr_code_scanner:
    git:
      url: https://github.com/juliuscanute/qr_code_scanner
  shared_preferences:
  http:
  flutter_sodium:
    git:
      url: https://github.com/rmtmckenzie/flutter_sodium
  package_info:
  uni_links:
    git:
      url: https://github.com/MathiasDeWeerdt/uni_links
  flutter_inappwebview:
    git:
      url: https://github.com/jimbertools/flutter_inappwebview
      ref: master
  cupertino_icons: ^0.1.2
  crypto: ^2.0.6
  bip39: ^1.0.3
  uuid: 2.0.4
  socket_io_client: ^0.9.7+1
  keyboard_visibility: 0.5.0
  community_material_icon:
  local_auth: 0.6.0
  url_launcher:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/circle_images/
    - assets/icons/
    - assets/
