apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "releaseName" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt

spec:
  tls:
    - hosts:
    {{- range $host := .Values.ingress.hosts }}
      - {{ $host.host.name }}
    {{- end }}
      secretName: {{ template "releaseName" . }}
  rules:
{{- range $host := .Values.ingress.hosts }}
  - host: {{ $host.host.name }}
    http:
      paths:
      - path: {{ $host.host.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $host.host.service }}
            port:
              number: 80
{{- end }}
